/**
 * JSON Extractor Types & Interfaces
 */

/**
 * Extraction methods used by the JSONExtractor.
 * Listed in order of preference/reliability.
 */
export enum ExtractionMethod {
  MARKDOWN_BLOCKS = 'markdown_blocks',
  REGEX_PATTERN = 'regex_pattern',
  BRACKET_MATCHING = 'bracket_matching',
  FALLBACK_TEXT = 'fallback_text'
}

/**
 * Result of a successful JSON extraction.
 */
export interface ExtractedJSON {
  data: unknown;
  method: ExtractionMethod;
  confidence: number;
}

/**
 * Detailed error information for failed extractions.
 */
export interface ParseError {
  type: 'JSON_PARSE_ERROR' | 'VALIDATION_ERROR' | 'EXTRACTION_ERROR';
  message: string;
  originalContent: string;
  attemptedMethods: ExtractionMethod[];
  suggestions: string[];
  timestamp: string;
  contentLength: number;
  failureReasons: MethodFailure[];
}

/**
 * Details about why a specific extraction method failed.
 */
export interface MethodFailure {
  method: ExtractionMethod;
  error: string;
  attemptedAt: string;
}

/**
 * Success tracking information for extraction methods.
 */
export interface ExtractionSuccess {
  method: ExtractionMethod;
  confidence: number;
  timestamp: string;
  retryCount: number;
  processingTimeMs: number;
}

/**
 * Metrics for tracking method effectiveness.
 */
export interface MethodMetrics {
  method: ExtractionMethod;
  successCount: number;
  failureCount: number;
  averageConfidence: number;
  lastUsed: string | null;
}

/**
 * Result of JSON validation.
 */
export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  fixedData?: unknown;
  fieldErrors: FieldValidationError[];
  suggestions: string[];
}

/**
 * Detailed field-level validation error.
 */
export interface FieldValidationError {
  field: string;
  message: string;
  expectedType?: string;
  actualType?: string;
  suggestion?: string;
}

/**
 * Storyboard scene structure for validation.
 */
export interface StoryboardScene {
  scene?: number;
  prompt?: string;
  text?: string;
  mood?: string;
  timestamp?: string;
  confidence?: number;
  source?: 'llm' | 'fallback' | 'reconstructed';
}

/**
 * Storyboard structure for validation.
 */
export interface StoryboardData {
  prompts?: StoryboardScene[];
  scenes?: StoryboardScene[];
  visual_prompts?: StoryboardScene[];
  visualPrompts?: StoryboardScene[];
  storyboard?: StoryboardScene[];
  metadata?: Record<string, unknown>;
}

/**
 * Internal result type for extraction attempts.
 */
export interface ExtractionAttempt {
  success: boolean;
  data?: unknown;
  error?: string;
}

/**
 * Logger interface for customizable logging.
 */
export interface ExtractorLogger {
  info(message: string, data?: Record<string, unknown>): void;
  warn(message: string, data?: Record<string, unknown>): void;
  error(message: string, data?: Record<string, unknown>): void;
  debug(message: string, data?: Record<string, unknown>): void;
}

/**
 * Default console logger implementation.
 */
export const defaultLogger: ExtractorLogger = {
  info: (message, data) => console.log(`[JSONExtractor] INFO: ${message}`, data || ''),
  warn: (message, data) => console.warn(`[JSONExtractor] WARN: ${message}`, data || ''),
  error: (message, data) => console.error(`[JSONExtractor] ERROR: ${message}`, data || ''),
  debug: (message, data) => console.debug(`[JSONExtractor] DEBUG: ${message}`, data || ''),
};

// --- Fallback Processing Types ---

/**
 * Fallback notification callback type.
 */
export type FallbackNotificationCallback = (notification: FallbackNotification) => void;

/**
 * Fallback notification structure.
 */
export interface FallbackNotification {
  type: 'fallback_used';
  message: string;
  originalContentPreview: string;
  extractedPromptCount: number;
  timestamp: string;
  reducedFunctionality: string[];
}

/**
 * Fallback usage metrics.
 */
export interface FallbackMetrics {
  totalFallbackUsages: number;
  successfulFallbacks: number;
  failedFallbacks: number;
  averagePromptsExtracted: number;
  lastFallbackTimestamp: string | null;
  fallbackReasons: Map<string, number>;
}

/**
 * Basic storyboard structure generated by fallback processing.
 */
export interface BasicStoryboard {
  prompts: StoryboardScene[];
  metadata: {
    source: 'fallback';
    extractionMethod: 'text_based';
    confidence: number;
    originalContentLength: number;
    processingTimestamp: string;
    warnings: string[];
  };
}

/**
 * Result of text-based prompt extraction.
 */
export interface TextExtractionResult {
  prompts: string[];
  emotionalContent: string[];
  sceneDescriptions: string[];
  confidence: number;
}
